name: CI

on: [push]

jobs:
  test:
    name: Test on node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      fail-fast: true
      matrix:
        node_version:
          - 14
          - 16
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        architecture:
          - x64
    steps:
      - uses: actions/checkout@v2
      - name: Setup node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
          registry-url: https://registry.npmjs.org
      - name: Cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: install
        run: yarn install --frozen-lockfile
      - name: lint
        run: yarn lint
      - name: build
        run: yarn compile
      - name: test
        run: yarn test
        env:
          FORCE_EXIT: true
